apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS players (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL
    );

    INSERT INTO players (name) VALUES
      ('Shohei Ohtani'),
      ('Aaron Judge'),
      ('Juan Soto'),
      ('Andrew McCutcheon'),
      ('Vladimir Guerrero Jr.'); 