apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  username: "your_username"
  password: "your_password"
  database-url: "postgresql://your_username:your_password@postgres:5432/sport_stats" 