apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  username: "myuser"
  password: "mypassword"
  database-url: "postgresql://myuser:mypassword@postgres:5432/sport_stats" 