# Example Secret configuration - Copy this file to postgres-secret.yaml and replace the values
# Note: The values below need to be base64 encoded before using
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Base64 encode your values:
  # echo -n "your_value" | base64
  POSTGRES_USER: bXl1c2Vy                  # Default: myuser
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==      # Default: mypassword
  DATABASE_URL: cG9zdGdyZXNxbDovL215dXNlcjpteXBhc3N3b3JkQHBvc3RncmVzOjU0MzIvcG9zdGdyZXM=  # Default: postgresql://myuser:mypassword@postgres:5432/postgres 